server:
  port: 8001
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/zhuzhou
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver


mybatis:
  configuration:
    map-underscore-to-camel-case: true
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl